### ISSUE TITLE
Add poster image to movies

### ISSUE THREAD

**Issue by kassimariemc** [kassimariemc/project-1-operation-date-night#18]

**Comment by jhf1203** [comment]
I worked on this some tonight and wasn't successful but feel like I'm pretty close on a good idea:

- set all p and a tags within .movie-card-body to an opacity of 0
- set the background image for each card as the movie poster, so when it populates you see the card header and the poster.

Then...

$(".movie-card-body").hover(function(){
   $(this).css({"background-image":"none","background-color":"rgb(0, 48, 73)"})
   $($(this),p).css("opacity","1");
   $($(this),a).css("opacity","1");

} function () {
   **$($(this),p)..css({"background-image":"url(" + movie.Poster + ")","background-size":"100%"});**
   $($(this),p).css("opacity","0");
   $($(this),a).css("opacity","0");
});
________________________________________

unfortunately the bolded line to revert back to the poster once you no longer hover always changes back to the poster of the final of the three movies loaded, despite me placing this function within the for loop.  So if we return Forrest Gump, Heat, and City Of God when I hover over each individual poster it will show the movie details instead of the poster.  But when I "un-hover" the poster for all three will then be City Of God.

Really close on this, tried changing around everything I could think of, I feel like we could make this work if y'all have any ideas.  Maybe we can play with the index numbers of these elements, if the p and a tags can be on a separate index of the card body (don't think they can).  Or we can generate an img for the poster within the body, make it the same size as the body, clear fix it within the body, and make it disappear and reappear on hover?  Didn't get a chance to try those but they're my next best options.

**Comment by jhf1203** [comment]
Resolved with CSS
